# Tensors

`numpy` ndarrays that are optimized for use on GPU. To run a PyTorch Tensor on GPU, you use the `device` argument when constructing a Tensor to place the Tensor on a GPU.

```python
torch.device('cuda') # for GPU
torch.device('cpu') # for CPU
```



- A vector is a tensor of rank 1.
- A matrix is a tensor of rank 2.
- A color image is a tensor of rank 3.

![](https://nbviewer.jupyter.org/github/robert-alvarez/pytorch_tutorial/blob/master/data/img/tensor_viz.jpeg)

In [2]:
from __future__ import print_function
import torch
import numpy as np

In [60]:
torch.cuda.is_available()

True

In [62]:
torch.cuda.get_device_name()

'GeForce GTX TITAN X'

In [4]:
device = torch.device('cpu')
# device = torch.device('cuda') # Uncomment this to run on GPU

### Tensor Types

Torch defines eight CPU tensor types and eight GPU tensor types:

| Data type                | dtype                             | CPU Tensor           | GPU Tensor                |
|--------------------------|-----------------------------------|----------------------|---------------------------|
| 32-bit floating point    | `torch.float32` or `torch.float`  | `torch.FloatTensor`  | `torch.cuda.FloatTensor`  |
| 64-bit floating point    | `torch.float64` or `torch.double` | `torch.DoubleTensor` | `torch.cuda.DoubleTensor` |
| 16-bit floating point    | `torch.float16` or `torch.half`   | `torch.HalfTensor`   | `torch.cuda.HalfTensor`   |
| 8-bit integer (unsigned) | `torch.uint8`                     | `torch.ByteTensor`   | `torch.cuda.ByteTensor`   |
| 8-bit integer (signed)   | `torch.int8`                      | `torch.CharTensor`   | `torch.cuda.CharTensor`   |
| 16-bit integer (signed)  | `torch.int16` or `torch.short`    | `torch.ShortTensor`  | `torch.cuda.ShortTensor`  |
| 32-bit integer (signed)  | `torch.int32` or `torch.int`      | `torch.IntTensor`    | `torch.cuda.IntTensor`    |
| 64-bit integer (signed)  | `torch.int64` or `torch.long`     | `torch.LongTensor`   | `torch.cuda.LongTensor`   |

**Note**: Tensor types need to match when doing calculations with them.

# Creating a matrix - NumPy vs PyTorch

1. From scratch: Use similar methods to numpy, e.g. `torch.zeros`, `torch.ones`, `torch.empty`
2. From existing tensor: reuses properties of the input/existing tensor, e.g. dtype, unless otherwise specified
    - Use `new_*` methods
    - Use `torch.*_like` methods

## A matrix of zeroes

In [5]:
# numpy approach
np.zeros((5,3), dtype=np.float64)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
# PyTorch approach
torch.zeros((5,3), dtype=torch.float64)

# # This also works
# torch.zeros(5,3, dtype=torch.float64)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [35]:
x0 = torch.zeros(5, 3)
print(x0)

# Create a matrix of 1s from 
x1 = x0.new_ones(5, 3) # specify size/dim
print(x1)

x1_ = torch.rand_like(x)
print(x1_)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.6125, 0.4755, 0.7134],
        [0.8187, 0.0770, 0.6129],
        [0.4781, 0.7688, 0.0762],
        [0.2063, 0.0355, 0.1709],
        [0.5997, 0.4841, 0.4456]])


## An "empty" matrix

In [10]:
np.empty((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
torch.empty(5,3)

tensor([[-2.6232e-14,  0.0000e+00, -2.6232e-14],
        [ 0.0000e+00,         nan,  0.0000e+00],
        [ 1.7753e+28,  4.4339e+27,  1.3848e-14],
        [ 6.8801e+16,  1.8370e+25,  1.4603e-19],
        [ 6.8794e+11,  2.7253e+20,  3.0866e+29]])

## A matrix of random digits

In [12]:
np.random.rand(5,3)

array([[0.51528739, 0.049013  , 0.79415781],
       [0.0246596 , 0.88116879, 0.16948178],
       [0.55686797, 0.19753631, 0.66453021],
       [0.10042355, 0.0503528 , 0.88689164],
       [0.20948676, 0.87979173, 0.26528184]])

In [13]:
torch.rand(5,3)

tensor([[0.8021, 0.9577, 0.3992],
        [0.7849, 0.4673, 0.3456],
        [0.2115, 0.0196, 0.5886],
        [0.1148, 0.9573, 0.9425],
        [0.9122, 0.7613, 0.5390]])

## Create vector, matrix, etc. with your own values

In [23]:
np.array([1., 2, 3])

array([1., 2., 3.])

In [24]:
torch.tensor([1., 2, 3])

tensor([1., 2., 3.])

# Get the size and dimensions of a PyTorch Tensor

In [36]:
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

Here, we have `x`, which is a $5 \times 3$ matrix. A matrix is a tensor of rank 2.

Thus, for the `size()` method, we expect $5 \times 3$. And for the `dim()` method, we expect to get 2.

In [37]:
x.size()

torch.Size([5, 3])

In [39]:
x.dim()

2

# Resize/Reshape Tensors

In [58]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions

print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


# Convert NumPy object to PyTorch

Use `torch.from_numpy(numpy_object)`

In [21]:
mat_np = np.random.rand(5, 3)
print(mat_np)

# What type of object is it? Numpy ndarray
print(type(mat_np))

# What datatype does it hold?
print(mat_np.dtype)

[[0.84332758 0.98881949 0.06982325]
 [0.00865982 0.90165759 0.73502228]
 [0.98176297 0.15603668 0.18963717]
 [0.68240848 0.52178566 0.78008898]
 [0.03374405 0.20741808 0.21573672]]
<class 'numpy.ndarray'>
float64


In [22]:
mat_torch = torch.from_numpy(mat_np)
print(mat_torch)

# What type of object is it? torch Tensor object
print(type(mat_torch))

# What datatype does it hold?
print(mat_torch.dtype)

tensor([[0.8433, 0.9888, 0.0698],
        [0.0087, 0.9017, 0.7350],
        [0.9818, 0.1560, 0.1896],
        [0.6824, 0.5218, 0.7801],
        [0.0337, 0.2074, 0.2157]], dtype=torch.float64)
<class 'torch.Tensor'>
torch.float64


We can also convert a Tensor object to a NumPy array using `tensor_obj.numpy()`

In [59]:
back_to_np = mat_torch.numpy()

print(back_to_np)
print(type(back_to_np))
print(back_to_np.dtype)

[[0.84332758 0.98881949 0.06982325]
 [0.00865982 0.90165759 0.73502228]
 [0.98176297 0.15603668 0.18963717]
 [0.68240848 0.52178566 0.78008898]
 [0.03374405 0.20741808 0.21573672]]
<class 'numpy.ndarray'>
float64


# Tensor Operations

Operations require that the tensors be of the **same** `dtype`.

> In-place operations are followed by `_`, e.g. `y.add_(x)`, `x.copy_(z)`, `x.t_()`, etc.

Many methods:
1. `x + y`
2. `torch.add(x, y)`
3. Specify output tensor as argument: `torch.add(x, y, out=result)`
4. In-place: `y.add_(x)`

In [3]:
# A simple scalar addition

a = torch.FloatTensor([25])
b = torch.FloatTensor([30])
a + b

tensor([55.])

In [46]:
x = torch.rand(5, 3)
y = torch.rand(5, 3)
print(x)
print(y)

tensor([[0.7090, 0.3558, 0.0311],
        [0.3595, 0.4152, 0.0768],
        [1.0000, 0.7450, 0.8626],
        [0.5891, 0.8865, 0.8365],
        [0.6874, 0.5196, 0.7810]])
tensor([[0.5275, 0.9804, 0.9429],
        [0.1157, 0.7526, 0.2263],
        [0.3695, 0.0267, 0.4869],
        [0.9262, 0.9641, 0.0823],
        [0.2127, 0.9634, 0.1369]])


In [55]:
x + y

tensor([[1.2365, 1.3362, 0.9740],
        [0.4751, 1.1677, 0.3031],
        [1.3694, 0.7717, 1.3495],
        [1.5154, 1.8505, 0.9188],
        [0.9000, 1.4830, 0.9179]])

In [48]:
torch.add(x, y)

tensor([[1.2365, 1.3362, 0.9740],
        [0.4751, 1.1677, 0.3031],
        [1.3694, 0.7717, 1.3495],
        [1.5154, 1.8505, 0.9188],
        [0.9000, 1.4830, 0.9179]])

In [49]:
result = torch.zeros(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[1.2365, 1.3362, 0.9740],
        [0.4751, 1.1677, 0.3031],
        [1.3694, 0.7717, 1.3495],
        [1.5154, 1.8505, 0.9188],
        [0.9000, 1.4830, 0.9179]])


In [56]:
y.add_(x)

tensor([[1.2365, 1.3362, 0.9740],
        [0.4751, 1.1677, 0.3031],
        [1.3694, 0.7717, 1.3495],
        [1.5154, 1.8505, 0.9188],
        [0.9000, 1.4830, 0.9179]])