# AutoGrad

`torch.Tensor` is the central class of the package. If you set its attribute `.requires_grad = True`, it starts to track all operations on it. When you finish your computation you can call `.backward()` and have all the gradients computed automatically. The gradient for this tensor will be accumulated into `.grad` attribute.

Methods to _stop_ tracking:
1. call `.detach()` to detach it from the computation history, and to prevent future computation from being tracked
2. wrap the code block in `with torch.no_grad():`

Create a tensor and set requires_grad=True to track computation with it:

In [2]:
import torch
import numpy as np

In [3]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


What happens after we do a tensor operation?

In [4]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


`y` was created as a result of an operation, so it has a `grad_fn` (shown above as equal to `<AddBackward0>`. This information is kept in memory, which allows for easy backpropagation w/ `backward()`.

In [5]:
print(y.grad_fn)

Do more operations on `y`

In [6]:
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


# Gradients + Backprop

In [7]:
out.backward()

Now print the gradients for $\frac{\partial \ \text{out}}{\partial x}$

In [8]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


# Simple Example

In [15]:
a = torch.tensor([3.0, 2.0], requires_grad=True)
b = torch.tensor([4.0, 7.0])
ab_sum = a + b
print(ab_sum)

ab_res = (ab_sum*8).sum()
print(ab_res)

tensor([7., 9.], grad_fn=<AddBackward0>)
tensor(128., grad_fn=<SumBackward0>)


In [16]:
# Now calculate the gradient: d`ab_res`/d a
ab_res.backward()

print(a.grad)

tensor([8., 8.])
None


## Another example

1. Create a $2 \times 2$ matrix of 1s
2. Operations:
    1. Multiply by 3 and add 7
    2. Muliply the squared values by 2
    3. Calculate the mean
3. Calculate $\frac{\partial \ \text{w}}{\partial x}$

In [17]:
# Create a tensor and set requires_grad=True to track computation with it
x = torch.ones(2,2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [19]:
y = 3*x + 7
z = 2*y**2
w = z.mean()

print(z)
print(w)

tensor([[200., 200.],
        [200., 200.]], grad_fn=<MulBackward0>)
tensor(200., grad_fn=<MeanBackward0>)


In [20]:
# Backprop
w.backward()

# Gradient w.r.t x
x.grad

tensor([[30., 30.],
        [30., 30.]])